### ISSUE TITLE
误报

### ISSUE THREAD

**Issue by WilliamK7** [SiHaiYiYeQiu/SoftCnKiller#3]
![image](https://user-images.githubusercontent.com/82304956/167072721-5055acd8-f67a-4dde-b0a2-f14c46a08576.png)
quicklook 在 github 上开源，应该不是恶意软件
https://github.com/QL-Win/QuickLook

**Comment by dengyi-g** [comment]
看看文件路径是不是 temp，有时候在 temp 路径的软件会被误报为 流氓软件

**Comment by WilliamK7** [comment]
现在最新版已经没有问题了
